name: CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  preparar-entrega:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar versão de produção
        run: npm run build

      - name: Salvar artifact de produção
        uses: actions/upload-artifact@v7
        with:
          name: build-producao
          path: dist
          if-no-files-found: error


  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: preparar-entrega

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Baixar o código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar versão de produção
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v6

      - name: Preparar arquivos para publicação
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5